### ISSUE TITLE
Issue bundling plainlanguage.gov

### ISSUE THREAD

**Issue by petermgrund** [GSA/plainlanguage.gov#353]
## Summarize the issue in one sentence
I am running into an error when attempting to run 'bundle install' on a forked version of plainlanguage.gov. It says:
`Your bundle is locked to listen (3.2.1) from rubygems repository`.

## Tell us more about how we can help
I'm new to Ruby and not sure how to resolve this issue.

## Details

* Running a MacBook Pro M1

**Comment by petermgrund** [comment]
I was able to resolve that issue by running 'bundle update', but am now experiencing this error:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: basscss-sass/scss/basscss. Load paths: /Users/petergrund/Documents/PERSONAL_PROJECTS/plainlanguage.gov/_sass /Users/petergrund/Documents/PERSONAL_PROJECTS/plainlanguage.gov/_sass /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll_pages_api_search-0.5.0/lib/jekyll_pages_api_search/sass /opt/homebrew/lib/ruby/gems/3.0.0/gems/uswds-jekyll-1.4.1/_sass on line 7
```

```
jekyll 3.9.2 | Error:  File to import not found or unreadable: basscss-sass/scss/basscss.
Load paths:
  /Users/petergrund/Documents/PERSONAL_PROJECTS/plainlanguage.gov/_sass
  /Users/petergrund/Documents/PERSONAL_PROJECTS/plainlanguage.gov/_sass
  /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll_pages_api_search-0.5.0/lib/jekyll_pages_api_search/sass
  /opt/homebrew/lib/ruby/gems/3.0.0/gems/uswds-jekyll-1.4.1/_sass on line 7
/opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': File to import not found or unreadable: basscss-sass/scss/basscss. (Jekyll::Converters::Scss::SyntaxError)
Load paths:
  /Users/petergrund/Documents/PERSONAL_PROJECTS/plainlanguage.gov/_sass
  /Users/petergrund/Documents/PERSONAL_PROJECTS/plainlanguage.gov/_sass
  /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll_pages_api_search-0.5.0/lib/jekyll_pages_api_search/sass
  /opt/homebrew/lib/ruby/gems/3.0.0/gems/uswds-jekyll-1.4.1/_sass on line 7
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:118:in `convert'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:101:in `block in convert'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `reduce'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `convert'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:83:in `render_document'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:472:in `block in render_pages'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `render_pages'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:192:in `render'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:9:in `render'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/jekyll:23:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:483:in `exec'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:25:in `start'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/exe/bundle:48:in `block in <top (required)>'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/exe/bundle:36:in `<top (required)>'
	from /Users/petergrund/.gem/ruby/3.0.0/bin/bundle:23:in `load'
	from /Users/petergrund/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
(sass):7: File to import not found or unreadable: basscss-sass/scss/basscss. (Sass::SyntaxError)
Load paths:
  /Users/petergrund/Documents/PERSONAL_PROJECTS/plainlanguage.gov/_sass
  /Users/petergrund/Documents/PERSONAL_PROJECTS/plainlanguage.gov/_sass
  /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll_pages_api_search-0.5.0/lib/jekyll_pages_api_search/sass
  /opt/homebrew/lib/ruby/gems/3.0.0/gems/uswds-jekyll-1.4.1/_sass
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:67:in `rescue in import'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:44:in `import'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:28:in `imported_file'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:37:in `css_import?'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:310:in `visit_import'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `map'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `block in visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:157:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:10:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/root_node.rb:36:in `css_tree'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/root_node.rb:20:in `render'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/engine.rb:290:in `render'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass.rb:57:in `compile'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:119:in `convert'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:101:in `block in convert'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `reduce'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `convert'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:83:in `render_document'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:472:in `block in render_pages'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `render_pages'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:192:in `render'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:9:in `render'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/jekyll:23:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:483:in `exec'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:25:in `start'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/exe/bundle:48:in `block in <top (required)>'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/exe/bundle:36:in `<top (required)>'
	from /Users/petergrund/.gem/ruby/3.0.0/bin/bundle:23:in `load'
	from /Users/petergrund/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:65:in `import': File to import not found or unreadable: basscss-sass/scss/basscss. (Sass::SyntaxError)
Load paths:
  /Users/petergrund/Documents/PERSONAL_PROJECTS/plainlanguage.gov/_sass
  /Users/petergrund/Documents/PERSONAL_PROJECTS/plainlanguage.gov/_sass
  /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll_pages_api_search-0.5.0/lib/jekyll_pages_api_search/sass
  /opt/homebrew/lib/ruby/gems/3.0.0/gems/uswds-jekyll-1.4.1/_sass
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:28:in `imported_file'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:37:in `css_import?'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:310:in `visit_import'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `map'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `block in visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:157:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:10:in `visit'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/root_node.rb:36:in `css_tree'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/tree/root_node.rb:20:in `render'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass/engine.rb:290:in `render'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/sass-3.7.4/lib/sass.rb:57:in `compile'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:119:in `convert'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:101:in `block in convert'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `reduce'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `convert'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:83:in `render_document'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:472:in `block in render_pages'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `render_pages'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:192:in `render'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:9:in `render'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/jekyll:23:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:483:in `exec'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:25:in `start'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/exe/bundle:48:in `block in <top (required)>'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/petergrund/.gem/ruby/3.0.0/gems/bundler-2.3.13/exe/bundle:36:in `<top (required)>'
	from /Users/petergrund/.gem/ruby/3.0.0/bin/bundle:23:in `load'
	from /Users/petergrund/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'

```

**Comment by nick-mon1** [comment]
Peter, can you push your changes or create a branch on your fork?  It looks like it can't find a file that you added.
I don't see this is in the original repo.

`jekyll 3.9.2 | Error:  File to import not found or unreadable: basscss-sass/scss/basscss`

**Comment by nick-mon1** [comment]
I forked and clone the repo and resolved the above error by running these commands in order:

- bundle install
- bundle update
- npm install
- bundle exec jekyll serve

I see the following updates:

> ➜ bundle update 
> Fetching gem metadata from https://rubygems.org/..........
> Fetching gem metadata from https://rubygems.org/.
> Resolving dependencies...
> Using public_suffix 4.0.7 (was 4.0.6)
> Using addressable 2.8.0
> Using bundler 2.1.4
> Using colorator 1.1.0
> Using concurrent-ruby 1.1.10 (was 1.1.7)
> Using eventmachine 1.2.7
> Using http_parser.rb 0.8.0 (was 0.6.0)
> Using em-websocket 0.5.3 (was 0.5.1)
> Using ffi 1.15.5 (was 1.13.1)
> Using ethon 0.15.0 (was 0.12.0)
> Using forwardable-extended 2.6.0
> Using mercenary 0.3.6
> Using mini_portile2 2.8.0 (was 2.5.1)
> Using racc 1.6.0 (was 1.5.2)
> Using nokogiri 1.13.6 (x86_64-darwin) (was 1.11.4)
> Using parallel 1.22.1 (was 1.19.2)
> Using rainbow 3.1.1 (was 3.0.0)
> Using typhoeus 1.4.0
> Using yell 2.2.2
> Using html-proofer 3.19.3 (was 3.15.3)
> Using htmlentities 4.3.4
> Using i18n 0.9.5
> Using rb-fsevent 0.11.1 (was 0.10.4)
> Using rb-inotify 0.10.1
> Using sass-listen 4.0.0
> Using sass 3.7.4
> Using jekyll-sass-converter 1.5.2
> Using listen 3.7.1 (was 3.2.1)
> Using jekyll-watch 2.2.1
> Using rexml 3.2.5
> Using kramdown 2.4.0 (was 2.3.1)
> Using liquid 4.0.3
> Using pathutil 0.16.2
> Using rouge 3.28.0 (was 3.22.0)
> Using safe_yaml 1.0.5
> Using jekyll 3.9.2 (was 3.9.0)
> Using jekyll-redirect-from 0.16.0
> Using jekyll-sitemap 1.4.0
> Using jekyll_pages_api 0.1.6
> Using jekyll_pages_api_search 0.5.0
> Using kramdown-parser-gfm 1.1.0
> Using uswds-jekyll 1.4.1
> Bundle updated!

**Comment by petermgrund** [comment]
Thanks @nick-mon1, I got it working now.
